# Spring Cloud Gateway server port
server:
  port: 7070
management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 60s
        pool:
          max-idle-time: 20
      metrics:
        enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
  pid:
    file: ${instance.pid}
---
spring:
  config:
    activate:
      on-profile: local
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  recaptcha-url: https://www.google.com/recaptcha/api/siteverify
  slack-url: https://hooks.slack.com
  messenger-url: https://
  telegram-url: https://
  xangle-url: https://pro-api.xangle.io
---
spring:
  config:
    activate:
      on-profile: eks-dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  recaptcha-url: https://www.google.com/recaptcha/api/siteverify
  slack-url: https://hooks.slack.com
  messenger-url: https://
  telegram-url: https://
  xangle-url: https://pro-api.xangle.io
---
spring:
  config:
    activate:
      on-profile: eks-prod
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  recaptcha-url: https://www.google.com/recaptcha/api/siteverify
  slack-url: https://hooks.slack.com
  messenger-url: https://
  telegram-url: https://
  xangle-url: https://pro-api.xangle.io
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  recaptcha-url: https://www.google.com/recaptcha/api/siteverify
  slack-url: https://hooks.slack.com
  messenger-url: https://
  telegram-url: https://
  xangle-url: https://pro-api.xangle.io
---
spring:
  config:
    activate:
      on-profile: qa
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  recaptcha-url: https://www.google.com/recaptcha/api/siteverify
  slack-url: https://hooks.slack.com
  messenger-url: https://
  telegram-url: https://
  xangle-url: https://pro-api.xangle.io
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
sites:
  recaptcha-url: https://www.google.com/recaptcha/api/siteverify
  slack-url: https://hooks.slack.com
  messenger-url: https://
  telegram-url: https://
  xangle-url: https://pro-api.xangle.io